version: '2.1'
services:
  t-mobile:
    image: tomcat:9.0.6
    container_name: t-mobile
    ports:
      - "8080:8080"
    links:
      - t-mysql
      - t-activemq
    volumes:
      - ./target/TMobile-0.5-SNAPSHOT.war:/usr/local/tomcat/webapps/TMobile.war
      - ../target/log/tmobile:/usr/local/tomcat/logs/tmobile
    networks:
      - t_network

  t-activemq:
    image: rmohr/activemq:5.15.3
    container_name: t-activemq
    ports:
      - 8161:8161
      - 61616:61616
      - 61613:61613
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_STATIC_TOPICS: tmobile-topic
    #volumes:
      #- /activemq/activemq.xml:/conf/activemq.xml
      #- /container_data/activemq/data:/data/activemq
      #- /container_data/activemq/log:/var/log/activemq
    networks:
      - t_network

  t-mysql:
    image: mysql:5.7.21
    container_name: t-mysql
    hostname: t-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=provider
      - MYSQL_USER=provider_user
      - MYSQL_PASSWORD=qwerty
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
      - ./sql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: "/usr/bin/mysql --user=provider_user --password=qwerty --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 10s
      retries: 5
    networks:
      - t_network

  t-flyway:
    image: boxfuse/flyway:4.2.0
    container_name: t-flyway
    command: -url=jdbc:mysql://t-mysql:3306/provider -user=provider_user -password=qwerty -schemas=provider -baselineOnMigrate=true -baselineVersion=0.1 migrate
    volumes:
      - ./sql/provider:/flyway/sql
    depends_on:
      t-mysql:
        condition: service_healthy
    networks:
      - t_network

networks:
  t_network:
      driver: bridge


